// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttfqwxzkhtziaugfgeqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0ZnF3eHpraHR6aWF1Z2ZnZXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTkxMTcsImV4cCI6MjA2OTgzNTExN30.BxSvK-AfMfV5uDzFSxHeD4pVi03v0wnaTJWN79qFNxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});